codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false
comment:
  layout: "reach, diff, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: no
coverage:
  precision: 2
  round: up
  range: 90...100
  status:
    project:
      default:
        target: 95%
        threshold: 5%
        removed_code_behavior: adjust_base
    patch:
      default:
        target: auto
        threshold: 5%